package org.example.entity

import jakarta.persistence.*
import java.time.OffsetDateTime

@Entity
@Table(name = "videos")
class VideoEntity(

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "session_exercise_id", nullable = false)
    var sessionExercise: SessionExercisesEntity,

    @Column(name = "original_filename", nullable = false, columnDefinition = "text")
    var originalFilename: String,

    @Column(name = "content_type", nullable = false, columnDefinition = "text")
    var contentType: String,

    // The file is stored in Railway; these fields identify the stored object.
    @Column(name = "storage_bucket", nullable = false, columnDefinition = "text")
    var storageBucket: String,

    @Column(name = "storage_key", nullable = false, columnDefinition = "text")
    var storageKey: String,

    @Column(name = "byte_size", nullable = false)
    var byteSize: Long,

    @Column(name = "set_number")
    var setNumber: Int? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "upload_status", nullable = false, length = 16)
    var uploadStatus: VideoUploadStatus = VideoUploadStatus.PENDING,

    // Generated by the database when the metadata row is inserted.
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    var createdAt: OffsetDateTime? = null,

    // Set together with READY after the backend verifies the uploaded object.
    @Column(name = "uploaded_at")
    var uploadedAt: OffsetDateTime? = null,

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    var id: Long? = null,
)
